log "/var/log/bird.log" all;
log syslog { warning, error };

router id 10.20.0.47;

protocol device {
	scan time 60;
}

protocol bgp honeypot {
	local as 65001 port 179;
	neighbor range 0.0.0.0/0 external;
	passive yes;

	dynamic name "peer_";
	dynamic name digits 6;

	ipv4 {
		import all;
		import limit 5000;
		export none;
	};

	hold time 180;
	keepalive time 60;
	connect delay time 5;
	connect retry time 10;
	error wait time 30, 300;

	allow local as;
	allow bgp_local_pref yes;
	med metric on;
	default bgp_local_pref 100;

	multihop 10;

	debug { states, packets, routes };
}
